# Cargo.toml -- Cargo definition file for Tectonic.
# Copyright 2016-2020 the Tectonic Project
# Licensed under the MIT License.

[package]
name = "tectonic_engine_xetex"
version = "0.0.0-dev.0"  # assigned with cranko (see README)
authors = ["Peter Williams <peter@newton.cx>"]
build = "build.rs"
description = """
A modernized, complete, embeddable TeX/LaTeX engine. Tectonic is forked from the XeTeX
extension to the classic “Web2C” implementation of TeX and uses the TeXLive distribution
of support files.
"""
license = "MIT"
edition = "2018"
links = "tectonic_engine_xetex"


[build-dependencies]
cc = "^1.0.66"
pkg-config = "^0.3"
regex = "^1.4"
sha2 = "^0.9"
tectonic_cfg_support = { path = "../cfg_support", version = "0.0.0-dev.0" }
tectonic_dep_support = { path = "../dep_support", version = "0.0.0-dev.0" }
vcpkg = "0.2.11"
cbindgen = "0.16.0"

[dependencies]
app_dirs = { version = "2", package = "app_dirs2" }
atty = "0.2"
byte-unit = "^4.0"
cfg-if = "1.0"
error-chain = "^0.12"
flate2 = { version = "^1.0.19", default-features = false, features = ["zlib"] }
fs2 = "^0.4"
lazy_static = "^1.4"
libc = "^0.2"
md-5 = "^0.9"
open = "1.4.0"
serde = { version = "^1.0", features = ["derive"], optional = true }
sha2 = "^0.9"
structopt = "0.3"
tectonic_bridge_core = { path = "../bridge_core", version = "0.0.0-dev.0" }
tectonic_bridge_flate = { path = "../bridge_flate", version = "0.0.0-dev.0" }
tectonic_bridge_graphite2 = { path = "../bridge_graphite2", version = "0.0.0-dev.0" }
tectonic_bridge_harfbuzz = { path = "../bridge_harfbuzz", version = "0.0.0-dev.0" }
tectonic_bridge_icu = { path = "../bridge_icu", version = "0.0.0-dev.0" }
tectonic_engine_bibtex = { path = "../engine_bibtex", version = "0.0.0-dev.0" }
tectonic_engine_teckit = { path = "../engine_teckit" }
tectonic_engine_xdvipdfmx = { path = "../engine_xdvipdfmx" }
tectonic_errors = { path = "../errors", version = "0.0.0-dev.0" }
tectonic_geturl = { path = "../geturl", version = "0.0.0-dev.0", default-features = false }
tectonic_io_base = { path = "../io_base", version = "0.0.0-dev.0" }
tectonic_status_base = { path = "../status_base", version = "0.0.0-dev.0" }
tectonic_xdv = { path = "../xdv", version = "0.0.0-dev.0" }
tectonic_xetex_layout = { path = "../xetex_layout", version = "0.0.0-dev.0" }
tempfile = "^3.1"
termcolor = "^1.1"
toml = { version = "^0.5", optional = true }
url = "^2.0"
zip = { version = "^0.5", default-features = false, features = ["deflate"] }

[features]
default = ["geturl-reqwest", "serialization"]

# Note: we used to have this to couple "serde" and "serde-derive", but we've
# adopted the newer scheme to avoid having to depend on both -- should maybe
# just get rid of this feature:
serialization = ["serde", "toml"]

external-harfbuzz = ["tectonic_bridge_harfbuzz/external-harfbuzz"]

geturl-curl = ["tectonic_geturl/curl"]
geturl-reqwest = ["tectonic_geturl/reqwest"]

native-tls-vendored = ["tectonic_geturl/native-tls-vendored"]

# developer feature to compile with the necessary flags for profiling tectonic.
profile = []

[dev-dependencies]
filetime = "^0.2"
futures = "0.1"
headers = "0.2"
hyper = "0.12"
tempfile = "^3.1"
tokio = "0.1.22"

[package.metadata.vcpkg]
git = "https://github.com/microsoft/vcpkg"
rev = "50ea8c0ab7aca3bb9245bba7fc877ad2f2a4464c"

[package.metadata.vcpkg.target]
x86_64-apple-darwin = { install = ["freetype","harfbuzz[icu,graphite2]"] }
aarch64-apple-darwin = { triplet = "arm64-osx", install = ["freetype","harfbuzz[icu,graphite2]"] }
x86_64-unknown-linux-gnu = { install = ["fontconfig","freetype","harfbuzz[icu,graphite2]"] }
x86_64-pc-windows-msvc = { triplet = "x64-windows-static", install = ["fontconfig","freetype","harfbuzz[icu,graphite2]"] }

[package.metadata.internal_dep_versions]
tectonic_bridge_core = "thiscommit:2021-01-16:wie2Ejoh"
tectonic_bridge_flate = "thiscommit:2021-01-01:eer4ahL4"
tectonic_bridge_graphite2 = "2c1ffcd702a662c003bd3d7d0ca4d169784cb6ad"
tectonic_bridge_harfbuzz = "2c1ffcd702a662c003bd3d7d0ca4d169784cb6ad"
tectonic_bridge_icu = "2c1ffcd702a662c003bd3d7d0ca4d169784cb6ad"
tectonic_cfg_support = "thiscommit:aeRoo7oa"
tectonic_dep_support = "5faf4205bdd3d31101b749fc32857dd746f9e5bc"
tectonic_engine_bibtex = "thiscommit:2021-01-17:KuhaeG1e"
tectonic_errors = "317ae79ceaa2593fb56090e37bf1f5cc24213dd9"
tectonic_geturl = "thiscommit:2021-01-16:Aikoob9c"
tectonic_io_base = "thiscommit:2021-01-16:SaeK7eex"
tectonic_status_base = "317ae79ceaa2593fb56090e37bf1f5cc24213dd9"
tectonic_xdv = "c91f2ef37858d1a0a724a5c3ddc2f7ea46373c77"
tectonic_xetex_layout = "2c1ffcd702a662c003bd3d7d0ca4d169784cb6ad"